# Builder stage
FROM docker.io/library/golang:latest as builder
WORKDIR /src
COPY . .
RUN go build -o /app/main

# Final stage
FROM docker.io/library/alpine:latest
WORKDIR /app
COPY --from=builder /app .
RUN apk update && apk add --no-cache ansible gcompat openssh
ENTRYPOINT ["/app/main"]  # Entry point
