FROM docker.io/library/alpine:3.20

RUN apk add rsync

# COPY ./synchroniser /app
# COPY ./synchroniser/crontab /etc/cron.d/crontab

# RUN chmod +x /app/mirror.sh
COPY ./synchroniser/mirror.sh /etc/periodic/15min
RUN chmod +x /etc/periodic/15min/mirror.sh

CMD ["crond", "-f"]