---
- name: Add VPN user
  hosts: "{{ vpn_servers | default('vpn_servers') }}"
  gather_facts: false
  vars:
    wireguard_dir: "/etc/wireguard/"

  tasks:

    - name: Include task list in play only if the condition is true
      ansible.builtin.include_tasks: ./tasks/tasks_add_vpn_user.yaml
      loop: "{{ WIREGUARD_VPN_PSONO_SECRET_IDS }}"
      loop_control:
        loop_var: PSONO_SECRET_ID
