---
- name: Add VPN user
  hosts: "{{ vpn_servers | default('vpn_servers') }}"
  gather_facts: false
  become: yes
  vars:
    wireguard_dir: "/etc/wireguard/"

  tasks:

    - name: Generate new vpn peer config & Add save client config to password manager
      ansible.builtin.shell: |
        PSONO_CI_API_KEY_ID={{ PSONO_CI_API_KEY_ID }} PSONO_CI_API_SECRET_KEY_HEX={{ PSONO_CI_API_SECRET_KEY_HEX }} PSONO_CI_SERVER_URL={{ PSONO_CI_SERVER_URL }} PSONO_SECRET_ID={{ PSONO_SECRET_ID }} ./add-vpn-user.sh
        exit 0
      args:
        chdir: "{{ wireguard_dir }}"