---
- hosts: servers
  become: true
  tasks:
  - name: Debug
    ansible.builtin.debug:
      msg: "Running servers playbook"

  - name: Configure NTP client for time synchronization
    command: setup-ntp busybox

  - name: Set up apk-repo
    command: setup-apkrepos -f

  - name: Set up apk-repo
    command: apk update && apk add eudev && setup-devd udev
