---
#
# Bootstrap physical server from factory reset to booted
#
# - Install OpenZFS boot & root across first two disks
#
- hosts: servers
  become: true
  gather_facts: false
  tasks:
  - name: Debug
    ansible.builtin.debug:
      msg: "Running servers playbook"


  - name: Install python
    # TODO: Consider installing python3 during the alpine netboot image build instead of here 
    raw: test -e /usr/bin/python3 || apk add python3
    changed_when: false

  # template minimal (loopback*) /etc/network/interfaces 
  # during bootstrap (interfaces are already configured with global IPs at this point,
  # this is to satisfy `setup-ntp busybox` which can't operate on an
  # empty /etc/network/interfaces file.
  # *only loopback is needed because iPXE has configured interfaces already,
  # there's no need to persist that to disk since we're booted into a minumal
  # alpine image at this point (netboot) which will be blown away after
  # Fedora/persistant operating system is installed
  - name: Template /etc/network/interfaces
    ansible.builtin.template:
      src: etc/network/interfaces
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
    tags:
    - network

  - name: Configure NTP client for time synchronization
    command: setup-ntp busybox
    tags:
    - network

  - name: Template /etc/apk/repositories
    ansible.builtin.template:
      src: etc/apk/repositories
      dest: /etc/apk/repositories
      owner: root
      group: root
      mode: '0644'
    tags:
    - repositories

  # - name: Template ~/.vimrc
  #   ansible.builtin.template:
  #     src: ./.vimrc
  #     dest: /root/.vimrc
  #     owner: root
  #     group: root
  #     mode: '0644'
  #   tags:
  #   - dotfiles

  # template minimal (loopback*) /etc/network/interfaces 
  # during bootstrap (interfaces are already configured with global IPs at this point,
  # this is to satisfy `setup-ntp busybox` which can't operate on an
  # empty /etc/network/interfaces file.
  # *only loopback is needed because iPXE has configured interfaces already,
  # there's no need to persist that to disk since we're booted into a minumal
  # alpine image at this point (netboot) which will be blown away after
  # Fedora/persistant operating system is installed
  - name: Template /etc/network/interfaces
    ansible.builtin.template:
      src: etc/network/interfaces
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
    tags:
    - network

  - apk:
      name: eudev,lsblk,sgdisk,jq,wipefs
      update_cache: yes
    tags:
    - packages

  - name: Run udev
    command: setup-devd udev
    tags:
    - udev


  - name: Copy file wipe-all-disks.sh
    ansible.builtin.copy:
      src: ./scripts/wipe-all-disks.sh
      dest: /root/wipe-all-disks.sh
      owner: root
      group: root
      mode: '0755'
    tags:
    - scripts

  - name: Copy file install-fedora-root-on-zfs.sh
    ansible.builtin.copy:
      src: ./scripts/install-fedora-root-on-zfs.sh
      dest: /root/install-fedora-root-on-zfs.sh
      owner: root
      group: root
      mode: '0755'
    tags:
    - scripts

  - name: Disable swap during play
    command: swapoff -a
    tags:
    - swapoff
