---
- hosts: servers
  become: true
  tasks:
  - name: Debug
    ansible.builtin.debug:
      msg: "Running servers playbook"

  - name: Add source repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://deb.debian.org/debian bullseye main contrib
      state: present

  - name: Add source repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://deb.debian.org/debian bullseye-backports main contrib
      state: present


  - name: Install openssh-server
    ansible.builtin.apt:
      name: openssh-server
      state: latest

  - name: Install ZFS & related packages
    ansible.builtin.apt:
      pkg:
      - debootstrap
      - gdisk
      - dpkg-dev
      - linux-headers-amd64

  - name: Install zfsutils-linux
    ansible.builtin.apt:
      name: zfsutils-linux
      state: latest

  - name: Disable swap during play
    command: swapoff --all
