FROM ubuntu:latest

RUN apt update && apt install -y gcc binutils make perl liblzma-dev mtools mkisofs syslinux isolinux build-essential git

WORKDIR /build

RUN git clone https://github.com/ipxe/ipxe.git
WORKDIR /build/ipxe/src

CMD make bin/ipxe.iso EMBED=/input/${FILE} && mv bin/ipxe.iso /output