name: Add VPN User

on:
  workflow_dispatch:
    inputs:
      vpn_ip_address:
        description: 'vpn_ip_address'
        required: true
        default: '192.0.2.1'

      ssh_username:
        description: 'ssh_username'
        required: true
        default: 'root'

      PSONO_SECRET_ID:
        description: 'PSONO_SECRET_ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setting up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPN_SSH_PRIVATE_KEY }}

    - name: SSH into remote host
      run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.ssh_username }}@${{ inputs.vpn_ip_address }} "date"

    - name: Generate new vpn peer config & Add save client config to password manager
      run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.ssh_username }}@${{ inputs.vpn_ip_address }} -C "PSONO_CI_API_KEY_ID=${{ secrets.PSONO_CI_API_KEY_ID }} PSONO_CI_API_SECRET_KEY_HEX=${{ secrets.PSONO_CI_API_SECRET_KEY_HEX }} PSONO_CI_SERVER_URL=${{ secrets.PSONO_CI_SERVER_URL }} PSONO_SECRET_ID=${{ inputs.PSONO_SECRET_ID }} && cd /etc/wireguard && ./add-vpn-user.sh"


    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
