name: Respond to new issue and create branch
on:
  issues:
    types: [opened]

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get issue number and title
        id: issue
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=title::${{ github.event.issue.title }}"
          echo ISSUE_TITLE=`echo "${{ github.event.issue.title }}" | tr -cd '[:alnum:]-' | tr ' ' '-' | cut -c -60` >> $GITHUB_ENV

      - name: Create new branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: repo
        run: |
          git checkout -b "${{ steps.issue.outputs.number }}-${{ env.ISSUE_TITLE }}"
          git push -u origin HEAD

