name: Respond to new issue and create branch
on:
  issues:
    - opened

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get issue number and title
        id: issue
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=title::${{ github.event.issue.title }}"

      - name: Create new branch
        run: |
          git checkout -b "${{ steps.issue.outputs.number }}-${{ steps.issue.outputs.title }}"
          git push -u origin HEAD

