name: Build Alpine ZFS Netboot Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-alpine-zfs-netboot-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build alpine image
        run: |
          podman run  -it --rm -v $(pwd):/root/workdir alpine sh /root/workdir/build-alpine-netboot-zfs.sh

      - name: Setting up SSH key to publish netboot image
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BOOT_SERVER_SSH_PRIVATE_KEY }}
    
      - name: SSH into remote host
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.BOOT_SERVER_SSH_USERNAME }}@${{ secrets.BOOT_SERVER_IP_ADDRESS }} "date"


      - name: Patch alpine image
        run: |
          ./patch-alpine-netboot-image-with-zfs.sh

      - name: Publish alpine netboot image artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpine-zfs-netboot-image
          path: iso/*
