name: Build Alpine ZFS Netboot Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-alpine-zfs-netboot-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build alpine image
        run: |
          podman run  -it --rm -v $(pwd):/root/workdir alpine sh /root/workdir/build-alpine-netboot-zfs.sh

      - name: Publish alpine netboot image artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpine-netboot-image
          path: iso/*
