name: Auto create git branch upon new issue
on:
  issues:
    types: [opened, reopened]

jobs:
  create-issue-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get issue number and title
        id: issue
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=title::${{ github.event.issue.title }}"
          # Sanitize issue title to:
          # - alnum
          # - replace spaces with hyphen '-'
          # Example:
          # Given an issue title: "Fix the 2'nd bug in UI where there's a # in the form"
          # Becomes:
          #
          # Note there is a space here, to keep both '-' and spaces ' '
          echo ISSUE_BRANCH_NAME=`echo "${{ github.event.issue.title }}" | \
          # Remove non alpha/numeric chars
          tr -cd '[:alnum:]- ' | \
          # Convert spaces to hyphens '-'
          tr ' ' '-' | \
          # Remove double hyphens
          sed 's/--/-/' | \
          # Ensure lowercase branch name
          tr '[:upper:]' '[:lower:]' | \
          # Limit branch name to 60 characters
          cut -c -60` >> $GITHUB_ENV

      - name: Create new branch
        run: |
          echo "The issue branch name is ${{ env.ISSUE_BRANCH_NAME}} "
          git checkout -b "${{ steps.issue.outputs.number }}-${{ env.ISSUE_BRANCH_NAME }}"
          git push -u origin HEAD

      - name: Creating PR based on branch name ${{ github.ref_name }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Subscribie/subscribie/pulls \
          -d '{"title": "#${{ steps.issue.outputs.number }} ${{ env.ISSUE_BRANCH_NAME }}","body":"Pull request related issue: #${{ steps.issue.outputs.number }}. Please pull these awesome changes in!","head":"${{ steps.issue.outputs.number }}-${{ env.ISSUE_BRANCH_NAME }}","base":"master"}'
