name: Qemu
concurrency: qemu
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Deploy:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Install quemu
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y qemu-system
          
      - name: Run quemu
        run: |
          set -x
          qemu-system-x86_64 -cpu ?
          qemu-system-x86_64 -cdrom https://github.com/KarmaComputing/server-bootstrap/releases/latest/download/ipxe.iso -net nic -net user,hostfwd=tcp::2223-:22 -m 3072 -smp $(nproc) -nographic
          
