name: ci

on:
  push:
  workflow_dispatch:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        run: |
          apt install -y qemu
      - name: Run QEMU
        run: |
          ls -l
          qemu-system-x86_64
          
        
